# Run command:
# docker-compose -f docker-compose.prod.yml up -d --build

# Exit command:
# docker-compose down

services:
  backend:
    extends:
      file: docker-compose.yml
      service: backend
    container_name: backend
    build:
      args:
        ENV_MODE: prod
